site_name: pedipanol's guide to MML

nav:
    - Home: index.md
    - Introduction: intro.md
    - General MML:
        - mml.md
        - structure.md
        - basics.md
        - other.md
    - PMD MML:
        - pmd/intro.md
        - pmd/setup.md
        - pmd/usage.md
        - pmd/structure.md
        - pmd/sequence.md
        - pmd/chipcom.md
        - pmd/rhythm.md
        - pmd/pcm.md
        - pmd/ssgeg.md
        - pmd/fm3extend.md
        - pmd/tips.md
        - pmd/advanced.md
        
theme:
  name: readthedocs
  highlightjs: false

markdown_extensions:
  - codehilite:
      guess_lang: False
      noclasses: True