site_name: pedipanol's guide to MML

nav:
    - Home: index.md
    - Introduction: intro.md
    - General MML: basics.md
    - PMD:
        - pmd/intro.md
        - pmd/setup.md
        - pmd/structure.md
        - pmd/sequence.md
        - pmd/chipcom.md
        - pmd/rhythm.md
        - pmd/pcm.md
        - pmd/ssgeg.md
        - pmd/fm3extend.md
        - pmd/tips.md
        - pmd/advanced.md
        
theme:
  name: material
